name: easyware.io/get-release
description: Get release information from a GitHub repository
inputs:
  token:
    description: 'GitHub token'
    required: true
  release_name:
    description: 'Release name of the release. Takes preference over `tag_name`'
    required: false
  tag_name:
    description: 'Tag name of the release. Is ignored if `release_name` is informed'
    required: false
  owner:
    description: 'Owner of the repository'
    required: false
  repo:
    description: 'Name of the repository'
    required: false
  error-if-draft:
    description: 'Action fails if release is still a draft'
    required: false
    default: 'false'
  error-if-not-draft:
    description: 'Action fails if release is not a draft'
    required: false
    default: 'false'
  error-if-prerelease:
    description: 'Action fails if release is a prerelease'
    required: false
    default: 'false'
  error-if-not-prerelease:
    description: 'Action fails if release is not a prerelease'
    required: false
    default: 'false'
  error-if-published:
    description: 'Action fails if release is published'
    required: false
    default: 'false'
  error-if-not-found:
    description: 'Action fails if release is not found'
    required: false
    default: 'false'
outputs:
  id:
    description: 'ID of the release'
  name:
    description: 'Name of the release'
  tag_name:
    description: 'Tag name of the release'
  body:
    description: 'Body of the release'
  draft:
    description: 'Whether the release is a draft'
  prerelease:
    description: 'Whether the release is a prerelease'
  published:
    description: 'Whether the release is published'
  created_at:
    description: 'Creation date of the release'
  published_at:
    description: 'Publication date of the release'
  url:
    description: 'URL of the release'
  html_url:
    description: 'HTML URL of the release'
  assets_url:
    description: 'URL of the release assets'
  upload_url:
    description: 'URL for uploading assets to the release'
  tarball_url:
    description: 'URL of the release tarball'
  zipball_url:
    description: 'URL of the release zipball'
  node_id:
    description: 'Node ID of the release'
  author_login:
    description: 'Login of the release author'
  author_id:
    description: 'ID of the release author'
  author_node_id:
    description: 'Node ID of the release author'
  author_avatar_url:
    description: 'Avatar URL of the release author'
  author_html_url:
    description: 'HTML URL of the release author'
  author_followers_url:
    description: 'URL of the followers of the release author'
  author_following_url:
    description: 'URL of the users followed by the release author'
  author_gists_url:
    description: 'URL of the gists created by the release author'
  author_starred_url:
    description: 'URL of the repositories starred by the release author'
  author_subscriptions_url:
    description: 'URL of the subscriptions of the release author'
  author_organizations_url:
    description: 'URL of the organizations the release author belongs to'
  author_repos_url:
    description: 'URL of the repositories owned by the release author'
  author_events_url:
    description: 'URL of the events performed by the release author'
  author_received_events_url:
    description: 'URL of the events received by the release author'
  author_type:
    description: 'Type of the release author'
  author_site_admin:
    description: 'Whether the release author is a site admin'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: shield
  color: orange
