name: 'Gets the release data from GitHub'
description: 'Gets the release data from GitHub for a specific release based on the release tag.'
author: 'easyware.io'
inputs:
  tag:
    required: true
    description: 'Release tag to check'
  owner:
    required: false
    description: 'Owner of the repository'
  repo:
    required: false
    description: 'Repository name'
  token:
    required: true
    description: 'GitHub token'
outputs:
  data:
    description: 'The release data'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: shield
  color: orange
